name: sqler
description: Package for building SQL queries in Dart, focusing on MySQL support.
version: 1.1.2
repository: https://github.com/uproid/sqler

topics:
  - sql
  - mysql
  - sql-builder
  - dart

environment:
  sdk: ^3.7.2

dependencies:
  intl: ^0.20.2
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mysql_client: ^0.0.27
