name: Test Workflow

# Trigger the workflow on push and pull requests
on:
  - push

# Define jobs
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
        - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Init database
      run: |
        mysql --protocol=tcp -h 127.0.0.1 --port 3306 -u root -ptest -e "SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';"
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Set up Dart SDK
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    
    # Display Dart version
    - name: Display Dart version
      run: dart --version
    
    # Install dependencies
    - name: Install dependencies
      run: dart pub get
    
    # Verify dependencies
    - name: Verify dependencies
      run: dart pub deps
    
    # Run static analysis
    - name: Analyze code
      run: dart analyze --fatal-infos
    
    # Check code formatting
    - name: Check formatting
      run: dart format --output=none --set-exit-if-changed .
    
    # Run tests
    - name: Run tests
      run: dart test
    
    # Optional: Validate package for publishing
    - name: Validate package
      run: dart pub publish --dry-run
